title: Pye Phyoe Aung # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/pyephyoeaung/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="large" data-theme="light" data-type="HORIZONTAL" data-vanity="pyephyoeaung" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://mm.linkedin.com/in/pyephyoeaung?trk=profile-badge">Pye Phyoe Aung</a></div>
              
